import { ChangeDetectionStrategy, Component } from '@angular/core';

interface Heart {
  id: number;
  x: number;
  y: number;
  size: number;
  opacity: number;
  blur: number;
  duration: number;
  delay: number;
  driftX: number;
  driftY: number;
}

@Component({
  selector: 'app-heart-background',
  templateUrl: './heart-background.html',
  styleUrl: './heart-background.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeartBackground {
  protected readonly hearts: Heart[] = [
    {
      id: 1,
      x: -8,
      y: 4,
      size: 34,
      opacity: 0.14,
      blur: 1,
      duration: 34,
      delay: -4,
      driftX: 7,
      driftY: -5,
    },
    {
      id: 2,
      x: 66,
      y: -16,
      size: 40,
      opacity: 0.16,
      blur: 0,
      duration: 39,
      delay: -15,
      driftX: -8,
      driftY: 6,
    },
    {
      id: 3,
      x: 20,
      y: 12,
      size: 23,
      opacity: 0.11,
      blur: 2,
      duration: 31,
      delay: -9,
      driftX: 6,
      driftY: 8,
    },
    {
      id: 4,
      x: 43,
      y: 30,
      size: 17,
      opacity: 0.16,
      blur: 0,
      duration: 27,
      delay: -7,
      driftX: -5,
      driftY: -8,
    },
    {
      id: 5,
      x: 72,
      y: 42,
      size: 28,
      opacity: 0.13,
      blur: 1,
      duration: 37,
      delay: -19,
      driftX: 8,
      driftY: -6,
    },
    {
      id: 6,
      x: 5,
      y: 55,
      size: 20,
      opacity: 0.11,
      blur: 2,
      duration: 29,
      delay: -12,
      driftX: 4,
      driftY: -9,
    },
    {
      id: 7,
      x: 27,
      y: 58,
      size: 18,
      opacity: 0.14,
      blur: 0,
      duration: 33,
      delay: -16,
      driftX: -7,
      driftY: 5,
    },
    {
      id: 8,
      x: 53,
      y: 64,
      size: 19,
      opacity: 0.12,
      blur: 1,
      duration: 30,
      delay: -3,
      driftX: 6,
      driftY: -7,
    },
    {
      id: 9,
      x: 82,
      y: 62,
      size: 24,
      opacity: 0.16,
      blur: 0,
      duration: 36,
      delay: -11,
      driftX: -8,
      driftY: -5,
    },
  ];

  protected readonly sparkles: Heart[] = [
    {
      id: 101,
      x: 7,
      y: 9,
      size: 0.7,
      opacity: 0.85,
      blur: 0,
      duration: 12,
      delay: -3,
      driftX: 2,
      driftY: -4,
    },
    {
      id: 102,
      x: 31,
      y: 18,
      size: 0.5,
      opacity: 0.7,
      blur: 0,
      duration: 14,
      delay: -8,
      driftX: -2,
      driftY: -5,
    },
    {
      id: 103,
      x: 64,
      y: 31,
      size: 0.8,
      opacity: 0.7,
      blur: 0,
      duration: 16,
      delay: -5,
      driftX: 1,
      driftY: -4,
    },
    {
      id: 104,
      x: 88,
      y: 15,
      size: 0.6,
      opacity: 0.9,
      blur: 0,
      duration: 13,
      delay: -6,
      driftX: -2,
      driftY: -3,
    },
    {
      id: 105,
      x: 19,
      y: 66,
      size: 0.6,
      opacity: 0.8,
      blur: 0,
      duration: 15,
      delay: -4,
      driftX: 3,
      driftY: -5,
    },
    {
      id: 106,
      x: 58,
      y: 53,
      size: 0.5,
      opacity: 0.75,
      blur: 0,
      duration: 11,
      delay: -7,
      driftX: -2,
      driftY: -4,
    },
    {
      id: 107,
      x: 93,
      y: 44,
      size: 0.65,
      opacity: 0.8,
      blur: 0,
      duration: 17,
      delay: -2,
      driftX: 1,
      driftY: -5,
    },
  ];
}
